export const TAGS = ["<!DOCTYPE html>", "<html>", "<head>", "<title>", "<meta>", "<link>", "<style>", "<script>", "<noscript>", "<base>",
"<body>",
"<h1>", "<h2>", "<h3>", "<h4>", "<h5>", "<h6>",
"<p>", "<br>", "<hr>",
"<a>", "<img>",
"<ul>", "<ol>", "<li>",
"<div>", "<span>",
"<header>", "<nav>", "<main>", "<section>", "<article>", "<aside>", "<footer>",
"<address>", "<time>",
"<strong>", "<em>", "<b>", "<i>", "<u>", "<mark>", "<small>", "<sub>", "<sup>", "<del>", "<ins>", "<code>", "<pre>", "<kbd>", "<samp>", "<var>", "<abbr>", "<cite>", "<q>", "<blockquote>", "<dfn>", "<bdi>", "<bdo>", "<wbr>",
"<table>", "<caption>", "<thead>", "<tbody>", "<tfoot>", "<tr>", "<th>", "<td>", "<colgroup>", "<col>",
"<form>", "<label>", "<input>", "<textarea>", "<select>", "<option>", "<optgroup>", "<button>", "<fieldset>", "<legend>", "<datalist>", "<output>", "<progress>", "<meter>",
"<figure>", "<figcaption>",
"<audio>", "<video>", "<source>", "<track>",
"<canvas>", "<svg>",
"<details>", "<summary>", "<dialog>",
"<template>", "<slot>",
"<iframe>", "<embed>", "<object>", "<param>",
"<map>", "<area>",
"<dl>", "<dt>", "<dd>",
"<data>", "<picture>",
"<portal>"

]